language: node_js
node_js: node
cache:
  directories:
  - node_modules
services:
  - postgresql
before_script:
  - psql -c 'create database pop_test_db;' -U postgres
script:
  - npm install
  - npm run migrate
  - npm test
after_success:
  - npm run coveralls
